name: Tictail
favicon: null
layout_spectrum: 0.39867631904780865
typography_spectrum: 0.021794218802824616
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1b191e'
    - '#bdd6f5'
    - '#7595c8'
    - '#6e7063'
    - '#e7af8e'
  brandStrength: 0.8125
  lightness: 0.3494785714428872
  saturation: 0.9784259160514921
  rhythmicContrast: 0.840505467960611
purpose: []
